#!/usr/bin/env python

import roslib
import rospy
import sys
import time
import tf
import math

from hlpr_lookat.srv import LookAt, LookAtT, LookAtTS
from std_msgs.msg import Bool
from geometry_msgs.msg import Pose, PoseStamped, Vector3

class LookAtEEF():
  def __init__(self):
    self.toggle = True
    self.prevX = 0.0
    self.prevZ = 0.0

    lookat_topic = "/hlpr_lookat_vec3"

    # a clean wait for service (no extraneous warnings)
    while not rospy.is_shutdown():
      try:
        rospy.wait_for_service(lookat_topic, 10)
        break
      except Exception as e:
        if rospy.is_shutdown():
          return
        rospy.logwarn("Waiting for lookat server")
    if rospy.is_shutdown():
      return

    self.lookat = rospy.ServiceProxy(lookat_topic, LookAt)
    rospy.loginfo("Lookat eef server has connected to lookat server.")

    rospy.Subscriber("eef_pose", Pose, self.pose_cb, queue_size=1)
    rospy.Subscriber("set_lookat_eef", Bool, self.set_cb, queue_size=1)

  def set_cb(self, msg):
    self.toggle = msg.data
    if self.toggle:
      rospy.loginfo("Looking at EEF")
    else:
      rospy.loginfo("Stop looking at EEF")

  def pose_cb(self, msg):
    if not self.toggle:
      return

    pos = msg.position
    dx = pos.x - self.prevX
    dz = pos.z - self.prevZ
    dist = math.sqrt((dx ** 2) + (dz ** 2))

    # Don't need to send service command for all distances
    if dist < 0.05:
      return
    #print "dist: " + str(dist)
    self.prevX = pos.x
    self.prevZ = pos.z
    quat = msg.orientation
    orient = tf.transformations.euler_from_quaternion([quat.x,quat.y,quat.z,quat.w])
    self.eePose = [pos.x, pos.y, pos.z, orient[0], orient[1], orient[2]]
    print self.eePose
    self.lookatPos(self.eePose)

  def lookatPos(self, pos):
    #if pos[0] < 0.9:
    #  return
    try:
      vec = Vector3()
      vec.x = pos[0]
      vec.y = pos[1]
      vec.z = pos[2]
      self.lookat(vec)
    except rospy.ServiceException, e:
      print "Lookat service call failed: %s"%e


def main():
  rospy.init_node("hlpr_lookat_eef_server")
  lookat = LookAtEEF()
  rospy.spin()


if __name__== '__main__':
  main()

